[package]
name = "js"
version = "0.1.0"
authors = ["rinz13r"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = { version = "0.3", features = ["derive"] }
ressa = "0.7.0"
resast = "0.4.1"
